### ISSUE TITLE
Environment Variable doesn't merge list of maps

### ISSUE THREAD

**Issue by aequasi** [cloudposse/terraform-aws-codebuild#27]
https://github.com/cloudposse/terraform-aws-codebuild/blob/master/main.tf#L202

Here, where you join them, it doesn't seem like its joining right.

When specifying the following config:

```
environment_variables  = [{
        name  = "APP_SECRET"
        value = "some secret"
    }]
```

You get the error: 
```
Error: module.build.aws_codebuild_project.default: "environment.0.environment_variable.6.name": required field is not set



Error: module.build.aws_codebuild_project.default: "environment.0.environment_variable.6.value": required field is not set
```

**Comment by aequasi** [comment]
Oh weird.... This happens when the value is empty.

**Comment by tedder** [comment]
It also happens if late-binding interpolation is needed (like, if you are using `${data...}` in an environment var. It'll certainly be possible with tf12, but the current (tf11+this module's codebuild) method of passing and merging lists in the module, in this case, breaks under these circumstances.
